### ISSUE TITLE
When set span on whole text the text becomes invisible

### ISSUE THREAD

**Issue by mianaliasjad** [santaevpavel/OutlineSpan#2]
I am setting the span on whole text but there is a problem if a set it on complete text length then the text becomes invisible.

`        spannableString.setSpan(testSpan,0,txt.length(),Spannable.SPAN_INCLUSIVE_EXCLUSIVE);
`
If i set like this then it works:
`        spannableString.setSpan(testSpan,2,txt.length(),Spannable.SPAN_INCLUSIVE_EXCLUSIVE);
`
just set srtart to any other numbe than 0.

**Comment by santaevpavel** [comment]
Ok, will check it today.

**Comment by santaevpavel** [comment]
@mianaliasjad i had fixed the issue. Please, check it on version [0.1.1](https://github.com/santaevpavel/OutlineSpan/releases/tag/0.1.1)

**Comment by mianaliasjad** [comment]
> @mianaliasjad i had fixed the issue. Please, check it on version [0.1.1](https://github.com/santaevpavel/OutlineSpan/releases/tag/0.1.1)

Thanks
Appreciated.

**Comment by AkashKrx** [comment]
@santaevpavel Please update the readme with the latest version. As many developers like me will end up using the mentioned version in the Readme and will waste several hours like me.

**Comment by santaevpavel** [comment]
@skyyyme done. Thank you for feedback.
